### ISSUE TITLE
Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [SwanandD121/FeatherPerfect_fe#1]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Ext)

**Comment by SwanandD121** [comment]
@KiranBaliga sounds good, go ahead

**Comment by KiranBaliga** [comment]
@SwanandD121 Please review the PR and action accordingly. Thank you!
