### ISSUE TITLE
 [Feature]-Add OAuth Integration for Login/Registration Page

### ISSUE THREAD

**Issue by AdityaP700** [SwanandD121/FeatherPerfect_fe#108]
## Overview
Implement OAuth authentication in the Login and Registration page to allow users to sign up and log in using third-party platforms such as Google. This feature will enhance the user experience by providing a quick and secure way to access the application without the need for creating a new account with a password.
![image](https://github.com/user-attachments/assets/8528c44d-175b-4761-a6c6-6063452c799c)

**Comment by AdityaP700** [comment]
I have made similar changes before in some projects and with that Kindly let me know for any additional inputs . Thus assign me under GSSOC-extnd and HackoctoberFest with a Level . Thanks in Anticipation

**Comment by geetanjalidubey9** [comment]
plss assign me this issue

**Comment by SwanandD121** [comment]
Issue already present
