### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by vijaychandra1910** [SwanandD121/FeatherPerfect_fe#11]
![Screenshot 2024-10-01 234144](https://github.com/user-attachments/assets/cf20e52a-aa92-4f02-aace-6fe74910a4ce)

The website is not responsive. Make it responsive for clear work in all devices.

**Comment by SwanandD121** [comment]
@vijaychandra1910 go ahead

**Comment by Ajdecoder** [comment]
hey @SwanandD121 i would like to work on it i will make it responsice using tailwind css utilities and custom css
