### ISSUE TITLE
Add Functionality to Open Notification Modal on Click of Notification Icon

### ISSUE THREAD

**Issue by 17arindam** [SwanandD121/FeatherPerfect_fe#12]
Problem:
Currently, the notification icon exists in the app, but it doesn't trigger any action when clicked. Users should be able to click the notification icon and see a modal displaying all current notifications.

Suggested Solution:
Add an event listener or on-click handler to the notification icon.
It will open a notification modal which will be used to show the notifications
![image_2024-10-02_012947132](https://github.com/user-attachments/assets/513ca8ed-c893-448d-bc72-ff1de81b20a2)

**Comment by 17arindam** [comment]
Hii @SwanandD121 please assign me this issue

**Comment by SwanandD121** [comment]
@17arindam go ahead.
