### ISSUE TITLE
[ENHANCEMENT] : Making Better UI For Profile Data Card

### ISSUE THREAD

**Issue by vedanshjainvj** [SwanandD121/FeatherPerfect_fe#123]
**Describe The Enhancement**
While clicking on View Profile button, the profile page doesn't opened from top.

**Steps To Reproduce**
Steps to reproduce the behavior :

- Login
- Go to Homepage
- Click on View Profile Button

**Expected Behavior**
A better UI Card.

**Screenshots/Videos**
![Screenshot (467)](https://github.com/user-attachments/assets/fb9a5f22-e636-44e1-9d03-8dbd4598094e)

**Additional Context**
Na

**Comment by Pushpa472** [comment]
@SwanandD121 I want to contribute this project please assign me...

**Comment by SwanandD121** [comment]
I think the UI design in decent enough
