### ISSUE TITLE
[ENHANCEMENT] : Adding More Buttons & Options To Share Experience

### ISSUE THREAD

**Issue by vedanshjainvj** [SwanandD121/FeatherPerfect_fe#124]
**Describe The Enhancement**
UI needs an improvment along with additon of emojis, minor interactions.

**Steps To Reproduce**
Steps to reproduce the behavior :

- Login
- Go to Homepage
- Click on Share an Experience Button

**Expected Behavior**
A better UI Card with more interaction options.

**Screenshots/Videos**
![Screenshot (468)](https://github.com/user-attachments/assets/d44e8de9-13dd-4db8-b872-8306718c1fd8)

**Additional Context**
Na

**Comment by SwanandD121** [comment]
@vedanshjainvj assigned
