### ISSUE TITLE
[ENHANCEMENT] : More Details Can Be Displayed In Followers Card

### ISSUE THREAD

**Issue by vedanshjainvj** [SwanandD121/FeatherPerfect_fe#125]
**Describe The Enhancement**
UI needs an improvement along with the more details of your followers

**Steps To Reproduce**
Steps to reproduce the behavior :

- Login
- Go to Homepage
- Observe Your Followers card.

**Expected Behavior**
A better UI Card with more details of followers.

**Screenshots/Videos**
![Screenshot (469)](https://github.com/user-attachments/assets/47bdb644-5148-43e1-86d5-f523cd0b51af)

**Additional Context**
Na

**Comment by SwanandD121** [comment]
I think the Followers card is decent enough
