### ISSUE TITLE
Modification of README.md file & Creation of LICENSE File for project

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [SwanandD121/FeatherPerfect_fe#127]
### 1) Add  animated line separators
I would like to add line separators in the README.md file to separate sections and make the file more readable and attractive. 
![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Add a **Team section**
The Team section will look more organized and readable and let the Contributors know whom to contact if they face any issues.

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/d371122b-fa03-4a3b-ba29-c1941341e02b)

 I would like to update it and try to automate the process.
![image](https://github.com/user-attachments/assets/0a27fcaa-a19f-45cf-8ed2-7c19bbcfcf47)

## 2. Addition of a LICENSE File to the project
If a project does not have a **LICENSE** file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.
So, adding a **LICENSE** file is a best practice for open-source projects. I have added the LICENSE to your project and attached a reference image below to help you review the PR.
MIT LICENSE Reference:
![image](https://github.com/user-attachments/assets/c86b485a-b0c7-4717-8b0b-1a24191a3675)

I would like to work on the issue. Please assign it to me so that I can make the project more readable and attractive for the Contributors.

**Comment by SwanandD121** [comment]
@rajdeepchakraborty-rc Can't assign level label for minor documentation issue.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Can't assign level label for minor documentation issue.

@SwanandD121 That's fine. My primary aim is to help make projects scalable and readable for all contributors. Points are always a secondary thing. I have a few pending issues assigned to me. I will start with this work soon after I am done with them.

**Comment by rajdeepchakraborty-rc** [comment]
I will keep you updated about the work progress

**Comment by rajdeepchakraborty-rc** [comment]
Also can the hacktobest-accepted tag also not be added?

**Comment by rajdeepchakraborty-rc** [comment]
@SwanandD121 Really sorry for the delay. Had to finish the pending Issues assigned to me. Here are some updates of the work done

**Comment by rajdeepchakraborty-rc** [comment]
This is the LICENSE for your file:
![image](https://github.com/user-attachments/assets/08255548-4e4f-4a48-86d5-4d01ca88579b)

Please do let me know if it's fine for you

**Comment by rajdeepchakraborty-rc** [comment]
This is how the **Team Section** is looking for you:
![image](https://github.com/user-attachments/assets/ebbb012d-8470-41aa-80d0-0713021a17b2)

Hope you like it.

**Comment by rajdeepchakraborty-rc** [comment]
This is the updated Contributors Mention section:
![image](https://github.com/user-attachments/assets/5df7fcfb-868c-4eea-911d-daced3f6cb91)

**Comment by rajdeepchakraborty-rc** [comment]
These are the program acceptance banners that I have added so that the Contributors can easily figure out that this repository is participating in these open-source programs:
![image](https://github.com/user-attachments/assets/ebad3003-5581-42cc-8439-54e1dce20a86)

**Comment by rajdeepchakraborty-rc** [comment]
Do let me know your thoughts about the changes. I will add some finishing touches and open a PR tomorrow after getting your feedback on the work done.

**Comment by rajdeepchakraborty-rc** [comment]
Closed as resolved and merged in PR #161
