### ISSUE TITLE
BUG: Remember me btn in login page

### ISSUE THREAD

**Issue by harshbhar0629** [SwanandD121/FeatherPerfect_fe#129]
When we want to unmark the remember me button then it will not change its behaviour its always marked so when user clicked to that button to unmarked then it will unmarked.

See Behaviour:

https://github.com/user-attachments/assets/7a0011a7-95d3-456f-987b-292582a0cfd0

@SwanandD121 Please assign to me with the labels.

**Comment by SwanandD121** [comment]
I will reopen this after Auth is developed
