### ISSUE TITLE
Not having Email field in Signup page

### ISSUE THREAD

**Issue by harshbhar0629** [SwanandD121/FeatherPerfect_fe#130]
**Description:**
When user want to Signup or want to create account then instead of username please change the field to email because email is must for future purpose if your signup backend is there then how you can verify your account?? by using username but you can verify by using email.

Current UI:

![issueSignup](https://github.com/user-attachments/assets/18f487bb-d91b-4636-abf9-b5b96054e4d4)

@SwanandD121 Please review this issue and assigned to me with the labels.

**Comment by SwanandD121** [comment]
@harshbhar0629 assigned
