### ISSUE TITLE
Login and Signup functionality with Backend

### ISSUE THREAD

**Issue by harshbhar0629** [SwanandD121/FeatherPerfect_fe#134]
There is no login and signup functionality in the backend anyone can create its account and for same email having multiple account but when backend code is there it store in database and also check is this email is already registered or not and much more functionality are available.

@SwanandD121 Please assign to me with gssoc-ext, hacktoberfest-accepted, with level-3, because it required alot of code and we have to also connect to UI.

**Comment by harshbhar0629** [comment]
??

**Comment by SwanandD121** [comment]
duplicate issue
