### ISSUE TITLE
BUG: Follow btn Not Working

### ISSUE THREAD

**Issue by harshbhar0629** [SwanandD121/FeatherPerfect_fe#138]
In Home page they suggest some follower but when we click on follow button no change in button What i expected when we click on Follow btn then it will start following and when we click on unfollow then it unfollow to the user.

@SwanandD121 Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, with the level-2.

**Comment by SwanandD121** [comment]
I will reopen after backend integration
