### ISSUE TITLE
[Feature Request]: Adding animated footer to the website

### ISSUE THREAD

**Issue by GyanaPrakashSahoo7853** [SwanandD121/FeatherPerfect_fe#146]
Description 

The current website lacks footer part and social media icons to reach out to the particular admin of the website. Changing the footer into better looking and responsive features.

Screenshots

![Screenshot 2024-10-14 112219](https://github.com/user-attachments/assets/fc324727-4d56-4d84-b138-9588f25d9730)

**Comment by GyanaPrakashSahoo7853** [comment]
I would like to work on it. 
@SwanandD121 Please assign me this issue with label hacktoberfest and gssoc-extd .

**Comment by SaanyaGarg5** [comment]
you can assign this task to me..

**Comment by SwanandD121** [comment]
> you can assign this task to me..

This task is already assigned to @GyanaPrakashSahoo7853

**Comment by GyanaPrakashSahoo7853** [comment]
> > you can assign this task to me..
> 
> This task is already assigned to @GyanaPrakashSahoo7853 

I am having some doubts related to the folder and changes made in the folder can we please connect at discord

**Comment by GyanaPrakashSahoo7853** [comment]
Please clarify my doubts related to the files of websites
