### ISSUE TITLE
Issue: "Remember Me" Checkbox Permanently Checked

### ISSUE THREAD

**Issue by RishaubKumar** [SwanandD121/FeatherPerfect_fe#152]
Description:
The "Remember Me" checkbox on the login page is permanently checked and cannot be unchecked when clicked. This issue prevents users from toggling the checkbox on and off, which may cause undesired functionality. The checkbox should be user-interactive, allowing them to decide whether or not to stay logged in.
![Uploading featherPerfect.PNG…]()

**Comment by RishaubKumar** [comment]
I am working on it please assign it to me with GSSOC label

**Comment by RishaubKumar** [comment]
Issue resolved please review it and adhere me If any change needed.

**Comment by SwanandD121** [comment]
Dont create a PR if issue is not assigned to you
