### ISSUE TITLE
Adding header and footer

### ISSUE THREAD

**Issue by gurramkarthiknetha** [SwanandD121/FeatherPerfect_fe#153]
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/203db6cf-6d70-4728-affd-d7f9ce794c19">
and in header what something input is not appearing properly fix it 
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/dd78096a-b2fa-45cd-8bc4-f3ab903a4389">
there is no footer for thius page  
assin me under hacktoberfest please

**Comment by SwanandD121** [comment]
duplicate issue
