### ISSUE TITLE
Change dashboard layout

### ISSUE THREAD

**Issue by jainaryan04** [SwanandD121/FeatherPerfect_fe#155]
@SwanandD121 
There should be no other content in the region where the navbar is present. 

Changes suggested -
1) move the what's happening div down so that it is not in the same line as the navbar.
2)  home, notifications and other icons should be on the left with the search bar on the right
3) what's happening and trends today - these three divs should be in the same line, horizontally
4) increase the width of the posts block to increase focus on the posts and enhace user UI.
5) remove the user profile page from the landing page and add an icon in the navbar for the user to view and edit his profile
![image](https://github.com/user-attachments/assets/9f4e4460-0f5c-451e-b999-5b26ad1038ca)
 
6) increase the size of icons

![image](https://github.com/user-attachments/assets/2c6650ac-f9ab-4540-9f65-6e449e6d3600)

![image](https://github.com/user-attachments/assets/2ec8bdbb-a3a1-4ee0-86c7-fdcfd9c5d38e)

**Comment by SwanandD121** [comment]
duplicate
