### ISSUE TITLE
Adding toaster to make it more appealing 

### ISSUE THREAD

**Issue by ChandraST12** [SwanandD121/FeatherPerfect_fe#16]
When clicking on the login, logout, or signup button, a toaster notification will appear. 

I can help you implement this feature. I would be grateful if you could assign me this issue under the GSSoC-ext and Hacktoberfest labels. I am looking forward to working on this issue.

**Comment by SwanandD121** [comment]
@ChandraST12 go ahead.
It'll be good if you use Toastify. 
Also make sure you make the toasts theme-friendly.

**Comment by SwanandD121** [comment]
merged
