### ISSUE TITLE
Make the Entire Website Responsive for All Screen Sizes

### ISSUE THREAD

**Issue by srishti023** [SwanandD121/FeatherPerfect_fe#167]
The website is not fully responsive, leading to layout inconsistencies on different devices.

https://github.com/user-attachments/assets/31723ab3-a8a8-4a1e-a41a-2dd5232e669c

I want to make the whole website responsive . please assign me this issue.
Thankyou!

**Comment by SwanandD121** [comment]
This will be done after the homepage is redesigned.
