### ISSUE TITLE
A detailed Read Me File with all required instruction

### ISSUE THREAD

**Issue by Muskan-bhatt249** [SwanandD121/FeatherPerfect_fe#18]
I believe that the ReadMe.md file could be improved a lot. I can add all the instructions for the contributor they need to follow for contribution. I can clearly mention all the key highlight features and details about the  technologies used in it. Please provide a chance to contribute in the project.

**Comment by SwanandD121** [comment]
@Muskan-bhatt249 go ahead.
I just need a readme.md file and it should be according to the project. 
contributing.md file is being made by another contributor.
PS: Vite is used for the development.

**Comment by SwanandD121** [comment]
PR Merged!
