### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [SwanandD121/FeatherPerfect_fe#2]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add hacktoberfest or GSSoC24 Ext labels.

**Comment by SwanandD121** [comment]
@KiranBaliga go ahead

**Comment by KiranBaliga** [comment]
@SwanandD121 Please review the PR and action accordingly. Please add level1 and gssoc24-ext labels to the PR as well. Thank you!
