### ISSUE TITLE
[documentation] Add "How to Create a PR" section in CONTRIBUTING.md 

### ISSUE THREAD

**Issue by SwanandD121** [SwanandD121/FeatherPerfect_fe#23]
To streamline the contribution process, we need to add a section to the `CONTRIBUTING.md` file that outlines clear guidelines for creating pull requests (PRs). This will ensure that contributions follow a standard format and are easier to review. The section should cover:

- How to properly create and name branches.
- A checklist for opening PRs 
-- description
-- linking to issues
-- following coding standards

- Expectations for review and merging.

This will improve the quality and consistency of incoming PRs and make collaboration more efficient.

**Comment by Sourabh782** [comment]
@SwanandD121 can i work on this? I have previous knowledge of contributions as well and i am sure it would help me write a good guiding for new contributors

**Comment by SwanandD121** [comment]
@Sourabh782 go ahead

**Comment by Sourabh782** [comment]
Sure, ill make the pr till evening, Thanks.

**Comment by Sourabh782** [comment]
@SwanandD121 can i edit contribution.md entirely?

![Screenshot 2024-10-04 170939](https://github.com/user-attachments/assets/fcf1a6d9-046c-40b0-97f2-adbc1d87b351)
![Screenshot 2024-10-04 170927](https://github.com/user-attachments/assets/2984f395-ad0e-4542-9737-0a3a9fcb6e07)
![Screenshot 2024-10-04 170915](https://github.com/user-attachments/assets/c1fe7ab3-54d0-4a9c-bbbb-31422cd95f8c)
![Screenshot 2024-10-04 170906](https://github.com/user-attachments/assets/e567f1f7-6398-41f5-9ab1-c3ac55b21ea0)

Or just add "How to create a Pr" section in pre existing one?

**Comment by SwanandD121** [comment]
Have you started working on this?

**Comment by Sourabh782** [comment]
@SwanandD121 these screen shots are on new contributing.md

**Comment by SwanandD121** [comment]
Text on Discord

**Comment by Sourabh782** [comment]
sure
