### ISSUE TITLE
Addition of forget password option

### ISSUE THREAD

**Issue by Sourabh782** [SwanandD121/FeatherPerfect_fe#24]
When a user forgets his password, so i wanted to add a forget password option in frontend

![Screenshot 2024-10-03 064631](https://github.com/user-attachments/assets/838a134d-dd6f-4cbb-ae3b-ca56ea4387be)

it will help user to reclaim their account

pls assign this to me under gssoc-extd and hacktober

**Comment by SwanandD121** [comment]
Right now the auth is not implemented.
The forgot password feature can be implemented when the auth is functional, so this is not needed now.
