### ISSUE TITLE
Adding a custom designed favicon and title related to website's theme

### ISSUE THREAD

**Issue by Sourabh782** [SwanandD121/FeatherPerfect_fe#25]
Currently the website supports default title and favicon, i wanted to add a custom favicon

![Screenshot 2024-10-03 065455](https://github.com/user-attachments/assets/fe0fff6f-1853-43a1-9c55-47601cc47b1e)

pls assign me this unfer hacktober and gssoc-extd

**Comment by SwanandD121** [comment]
@Sourabh782 go ahead

**Comment by Sourabh782** [comment]
Thanks for assigning, i will make pr on all 3 issues till evening
