### ISSUE TITLE
Addition of hide/view password on both login and signup page

### ISSUE THREAD

**Issue by Sourabh782** [SwanandD121/FeatherPerfect_fe#26]
The password should not be visible and be in hidden format, so i wanted to add functionality to hide and show password

![Screenshot 2024-10-03 065154](https://github.com/user-attachments/assets/61c149b3-408d-4044-830a-645dbf50084d)

pls assign this to me under hactober and gssoc-extd

**Comment by SwanandD121** [comment]
@Sourabh782 go ahead.
Add the eye icon on the right of password field to view or hide password

**Comment by Sourabh782** [comment]
Thanks for assiging, 
sure i'll add eye icon
