### ISSUE TITLE
feat: Improve scroll bar view

### ISSUE THREAD

**Issue by prajwaln07** [SwanandD121/FeatherPerfect_fe#27]
**before:**

https://github.com/user-attachments/assets/4ea97fdb-9ea6-42fd-b528-8f632336583b

**after:**

https://github.com/user-attachments/assets/1de4a8a2-e2de-4810-a651-58cd6ff9110c

I think it looks more appealing, don’t you?
@SwanandD121 can you assing me this issue ?

**Comment by SwanandD121** [comment]
@prajwaln07 assigned.
Make sure you link this issue while creating the PR.
