### ISSUE TITLE
[Feature]: There is no header present in any of the page.

### ISSUE THREAD

**Issue by muhafiz5814** [SwanandD121/FeatherPerfect_fe#28]
**Description**
None of the page `/`, `/home` and `/profile` has header at the top. It's always good to have a header in a website to look good and increased functionality.

**Steps to Reproduce**
I will create a header compatible with existing design.
Add a logo heading on the header.
Integrate links to login/sign up.

**Expected Behavior**
After implementing the header it will allow users to navigate to home page from any page, allow new users to navigate to signup and login page. Allow logged in users to navigate to profile page.

**Screenshots**
![feather perfect ](https://github.com/user-attachments/assets/74134dbb-c4c9-4097-9491-dd8885403058)
![feather perfect home](https://github.com/user-attachments/assets/75dd7ed1-f395-4a78-800f-1734a0162ef3)
![feather perfect profile](https://github.com/user-attachments/assets/8806369e-ad72-45cf-bf03-098f6e3757c4)

**Environment**
Operating System: Windows

**Additional Context**
I would like you to assign this issue to me so I can start working on it as soon as possible.

**Comment by muhafiz5814** [comment]
Thanks @SwanandD121 for assignment, I will try to complete it as soon as possible.

**Comment by SwanandD121** [comment]
@muhafiz5814 go ahead.
Name the component Navbar instead of Header

**Comment by muhafiz5814** [comment]
> @muhafiz5814 go ahead. Name the component Navbar instead of Header

Okay 👍
