### ISSUE TITLE
Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [SwanandD121/FeatherPerfect_fe#29]
Hello I can add client side input validations for the login and register pages
Pls assign this issue under hacktoberfest and gssoc extd

Thank you

**Comment by SwanandD121** [comment]
@Gauravtb2253 go ahead

**Comment by ArthKulkarni93** [comment]
@Gauravtb2253 are you working on it? 
If not I'd love do it today

**Comment by Keshav-1803** [comment]
It's been 2 weeks and this issue is not yet resolved.... If this is still open can you please assign this to me ??

**Comment by SwanandD121** [comment]
issue resolved
