### ISSUE TITLE
[bug] login page logo full not visible

### ISSUE THREAD

**Issue by Vinayyy19** [SwanandD121/FeatherPerfect_fe#3]
### Description

The logo on the sign-up page is cut off at the bottom.

### Steps to Reproduce

1. Go to the repository live link: [https://feather-perfect-fe.vercel.app/](https://feather-perfect-fe.vercel.app/)
2. Navigate to the sign-up page.

### Expected Behavior

The logo should be fully visible and not cut off.

### Actual Behavior

The logo is cut off at the bottom.

### Screenshots

![image](https://github.com/user-attachments/assets/c01bf6be-deda-4215-8a81-cfb26b819070)

### Environment

- **OS:** Windows 10
- **Browser:** Chrome

**Comment by Vinayyy19** [comment]
hii @SwanandD121,
can you assign me this to solve also can you label it.

**Comment by SwanandD121** [comment]
@Vinayyy19 go ahead.
