### ISSUE TITLE
Feature Request: Enhance the UI/UX of Authentication Flow (Sign-In, Sign-Up)

### ISSUE THREAD

**Issue by AlaminPu1007** [SwanandD121/FeatherPerfect_fe#30]
I would like to propose enhancements to the existing authentication flow, specifically the sign-in and sign-up pages. While the current design is functional and aesthetically pleasing, there are opportunities to further improve the user experience and make the interface more visually engaging.

1. Modern Look
2. Enhanced Usability
3. Consistency

**Comment by SwanandD121** [comment]
@AlaminPu1007 lets see what you have in mind

**Comment by nishakp3005** [comment]
@SwanandD121 can I work on this as well?
