### ISSUE TITLE
[Feature enhancement] : dark mode toggle.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [SwanandD121/FeatherPerfect_fe#35]
### **Is your feature request related to a problem? Please describe.**
there is not preferences in the website to toggle between dark and light mode.I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode.

**Comment by AlaminPu1007** [comment]
@SwanandD121 This issue is also updated with my pull request.
Can_Check #42
