### ISSUE TITLE
Dark mode is not working

### ISSUE THREAD

**Issue by iamsohelx** [SwanandD121/FeatherPerfect_fe#4]
Hii @SwanandD121 in your social media website the darkmode is not working.

**Comment by iamsohelx** [comment]
Hiii @SwanandD121 i can help you to fix this issue please, assign me this issue with labels

**Comment by SwanandD121** [comment]
@iamsohelx please go ahead

**Comment by Monu2114** [comment]
can u assign this task to me ?? with the same labels ?

**Comment by iamsohelx** [comment]
@Monu2114 i am already working on this brother

**Comment by SwanandD121** [comment]
closed.
