### ISSUE TITLE
adding map feature

### ISSUE THREAD

**Issue by Harshita9412** [SwanandD121/FeatherPerfect_fe#44]
hi @SwanandD121 ,
 
In this project, we can a Map feature, where which will allow users to upload their photos along with geographical tags, enabling others to view photos on an interactive map based on location.

I would love to take on the implementation of this features.

**Comment by SwanandD121** [comment]
Hey @Harshita9412  the backend of the project is not yet developed. The map feature will only work only after the photo uploading feature is added. 
I'll reopen this issue once the photo uploading is set up.
