### ISSUE TITLE
Like Option not working

### ISSUE THREAD

**Issue by Monu2114** [SwanandD121/FeatherPerfect_fe#45]
The post's like option is not getting colored when hitting the link button. Pls assign this task to me

**Comment by SwanandD121** [comment]
@Monu2114 Can you increase the like count on clicking on the like button?
If yes, I can assign.

**Comment by Monu2114** [comment]
> @Monu2114 Can you increase the like count on clicking on the like button?
> If yes, I can assign.

Yeah I can

**Comment by SwanandD121** [comment]
@Monu2114 assigned.
