### ISSUE TITLE
feat: Notification modal implementation

### ISSUE THREAD

**Issue by prajwaln07** [SwanandD121/FeatherPerfect_fe#47]
@SwanandD121  Modify the notification modal to display relevant notifications for a social media platform designed for wildlife photographers. Notifications should include new followers, comments on photos, featured photos, contest wins, and successful photo uploads.

@SwanandD121  is this fine :
 

https://github.com/user-attachments/assets/dcbf87e6-0205-48f2-b59e-1490df6595c3

**Comment by SwanandD121** [comment]
already done
