### ISSUE TITLE
Bug - Autocomplete needs to be turned Off 

### ISSUE THREAD

**Issue by maitri-vv** [SwanandD121/FeatherPerfect_fe#49]
There is a bug in thr form for the input field of username there is many user's entered usernames which are saved automatically hence to have privacy it needs to be turned off and previously entered data can be prevented from being exposed 
![image](https://github.com/user-attachments/assets/5d749bfe-d349-4fc0-a2f1-bd0a380975fc)

**Comment by SwanandD121** [comment]
@maitri-vv The autocomplete shows the data entered only by us and not any other user. So I think this does not breach security in any way.
