### ISSUE TITLE
feat: add toasts when login/logout

### ISSUE THREAD

**Issue by prajwaln07** [SwanandD121/FeatherPerfect_fe#51]
@SwanandD121 
i think we should add some toast when user do logout or login.
@SwanandD121  please assign me this .

**Comment by prajwaln07** [comment]
@SwanandD121  share your views on this .

**Comment by prajwaln07** [comment]
# before

https://github.com/user-attachments/assets/f71443f1-fff3-498d-b480-c70e9c46b3fb

# after

https://github.com/user-attachments/assets/e6bcc785-5366-4640-a76d-40ec8ea20c21

**Comment by prajwaln07** [comment]
@SwanandD121  please reply .

**Comment by SwanandD121** [comment]
@prajwaln07 go ahead.
And take a deep breath, Project admins don't do this full time, we also have other work to do.
Be patient.

**Comment by prajwaln07** [comment]
> @prajwaln07 go ahead.
> And take a deep breath, Project admins don't do this full time, we also have other work to do.
> Be patient.

Sorry if I seemed impatient, and I appreciate all the hard work you do. I’ll be more patient moving forward.
