### ISSUE TITLE
User Not Notified Upon Account Creation

### ISSUE THREAD

**Issue by RaiDevX8** [SwanandD121/FeatherPerfect_fe#53]
Currently, when a user creates an account, the account is successfully created, but there is no notification or visual indication informing the user that the account creation was successful. This can lead to confusion as users might attempt to create the account multiple times or believe the process has failed

@SwanandD121 @Untitled1rl 

Implement a notification system (toast message or page redirection) to notify users that their account has been created successfully

I Am happy to contribute !!

**Comment by SwanandD121** [comment]
issue already present
