### ISSUE TITLE
Footer Section and UI issue

### ISSUE THREAD

**Issue by NishantRana07** [SwanandD121/FeatherPerfect_fe#56]
It have a UI issue 

![Screenshot 2024-10-05 091654](https://github.com/user-attachments/assets/879b31ac-731b-4469-9fbd-927ee82137be)

and also there is no footer So I can implement that in it

@SwanandD121  Please assign it me bro

**Comment by SwanandD121** [comment]
Homepage UI is already being developed by another contributor.
