### ISSUE TITLE
Inconsistency in login/signup

### ISSUE THREAD

**Issue by eshaalal** [SwanandD121/FeatherPerfect_fe#65]
In the signup part no gmail is asked but in the login part gmail is asked

![Screenshot 2024-10-07 104935](https://github.com/user-attachments/assets/85aadbf3-28e9-4fb4-bace-98d52114543a)
![Screenshot 2024-10-07 104944](https://github.com/user-attachments/assets/1bd61042-7daa-4284-ac6b-2bd021fb87e0)

**Comment by SwanandD121** [comment]
issue already present
