### ISSUE TITLE
[bug] sign in button not working 

### ISSUE THREAD

**Issue by RiyaJain8114** [SwanandD121/FeatherPerfect_fe#66]
![image](https://github.com/user-attachments/assets/5db0769d-bb46-4902-90ba-158fda127a81)
 not screen showing up after clicking sign in

**Comment by geetanjalidubey9** [comment]
plss assign this task to me i would really like to work on it

**Comment by SwanandD121** [comment]
@RiyaJain8114 assigned.
Auth is being developed. For now, just redirect to login page after clicking on Sign In.

**Comment by mohdazam0786** [comment]
@SwanandD121 please sir assign this task to me

**Comment by vishesh1525** [comment]
@SwanandD121 Sir Can you assign this issue to me i will solve it by today 
there is a problem in sign up page 
once user submits the all the details the page should navigate to login but its not i can correct it can you assign me the work

**Comment by SwanandD121** [comment]
issue closed
