### ISSUE TITLE
[Enhancement] Make the Explore consistent width

### ISSUE THREAD

**Issue by leonyangela** [SwanandD121/FeatherPerfect_fe#67]
Hi, please assign this to me.

I'd like to make the explore input more consistent so it has the same width with the profile to have a better UI.

![image](https://github.com/user-attachments/assets/531db1a6-564e-4716-b75f-6e6157a54f59)

**Comment by SwanandD121** [comment]
@leonyangela go ahead

**Comment by leonyangela** [comment]
Hi @SwanandD121, thanks for assigning me, it's already in PR #68, thank you, cheers.

**Comment by SwanandD121** [comment]
merged
