### ISSUE TITLE
Implement JWT Authentication for Login, Logout, and Signup

### ISSUE THREAD

**Issue by prajwaln07** [SwanandD121/FeatherPerfect_fe#71]
Currently, the login, logout, and signup processes lack secure authentication. This issue aims to implement JWT (JSON Web Token) authentication for these actions to enhance security and ensure user data integrity. JWT will be used for generating tokens during login and signup, and for verifying tokens during logout to ensure secure user sessions.
@SwanandD121

**Comment by SwanandD121** [comment]
duplicate issue
