### ISSUE TITLE
Bug: Remember me is always checked

### ISSUE THREAD

**Issue by SalehaTabassum** [SwanandD121/FeatherPerfect_fe#75]
hello @SwanandD121 
In the login page the checkbox for remember me is always checked.
i would like to add the feature to check and uncheck it.
![Screenshot 2024-10-07 231707](https://github.com/user-attachments/assets/40b3b0a8-7880-40ce-9589-219865587b77)
 Could you please assign this issue to me

**Comment by SwanandD121** [comment]
minor issue, will be taken care of.
