### ISSUE TITLE
Add Google Authentication to Signup and Login Pages and Correct the Authentication Flow

### ISSUE THREAD

**Issue by rudrapratap63** [SwanandD121/FeatherPerfect_fe#79]
I would like to propose enhancements to both the signup and login pages by adding Google authentication functionality. This feature would allow users to easily sign up or log in using their Google accounts, improving user experience and convenience.

Additionally, I would like to implement `JWT Authentication` to further secure and streamline the authentication process.

https://github.com/user-attachments/assets/a2f80355-9319-4329-9739-56a4dad16030

❗And also, your login button is not working; it directly redirects the user to the home page.

**Comment by rudrapratap63** [comment]
@SwanandD121 Sir let me know if you want any other improvements.

**Comment by rudrapratap63** [comment]
Thank you for the clarification! I’ll comment on issue #39 as suggested. I’ll also ensure I work on the responsiveness of all pages. I’ll make sure to fetch the latest changes from the develop branch and submit the PR to the same branch.

Appreciate your guidance!

**Comment by SwanandD121** [comment]
@rudrapratap63 auth is being redeveloped by another contributor.
