### ISSUE TITLE
No signup page navigation 

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [SwanandD121/FeatherPerfect_fe#8]
![Screenshot_2024-10-01-23-02-46-609_com android chrome](https://github.com/user-attachments/assets/177261aa-64e5-4ad7-bc99-d93d1df72c83)

If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well
@SwanandD121

**Comment by SwanandD121** [comment]
@Sureshwebdeveloper Signup function is already created, you just need to link it at the right place.

**Comment by Sureshwebdeveloper** [comment]
Sure I will work on that as soon as possible

**Comment by SwanandD121** [comment]
closed.
