### ISSUE TITLE
Improving UI for  whats happening buttons

### ISSUE THREAD

**Issue by swamimalode07** [SwanandD121/FeatherPerfect_fe#82]
Improving UI for  whats happening buttons
![image](https://github.com/user-attachments/assets/fcc4daa1-453f-4f92-add7-43b6e0f4559b)

kindly assign me hacktoberfest-accepted and gssoc-extd level 1 or 2

**Comment by SwanandD121** [comment]
@swamimalode07 assigned

**Comment by swamimalode07** [comment]
I'll make a PR as soon as possible

**Comment by swamimalode07** [comment]
![image](https://github.com/user-attachments/assets/493309e3-33e4-47d8-a1e8-2b367badcda8)
I have done this changes , if you are good with this , should i make a pull request

**Comment by swamimalode07** [comment]
Hey @SwanandD121  I have made a pull request
[PR Link](https://github.com/SwanandD121/FeatherPerfect_fe/pull/126)

Can you please mark this PR level 2 or 3 for gssoc-extd
