### ISSUE TITLE
converting create react app to vite

### ISSUE THREAD

**Issue by Ajdecoder** [SwanandD121/FeatherPerfect_fe#83]
@SwanandD121  converting cra to vite to enhance development experience to increase versatility of the website development across developers and enhance development speed by 65%

**Comment by SwanandD121** [comment]
Its already on vite

**Comment by Ajdecoder** [comment]
sir probably there is some miscommunication as i can see this web app is bundled with cra
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
please correct if i am wrong
