### ISSUE TITLE
lets make it responsive

### ISSUE THREAD

**Issue by Ajdecoder** [SwanandD121/FeatherPerfect_fe#84]
The website is not at all responsive
before heading further we need to make it responsive by using tailwind utilities or writing custom css media queries also files 

![image](https://github.com/user-attachments/assets/d762b03d-b36b-4fd7-a2e5-b188263fc587)

![image](https://github.com/user-attachments/assets/ce29ce1e-f748-44b0-a273-ea1404065821)

![image](https://github.com/user-attachments/assets/58435009-df79-492f-bb69-059e71f7e7a7)

**Comment by SwanandD121** [comment]
this will be done during redesigning of homepage
