### ISSUE TITLE
replace hyperlink with a toggle button to switch between light mode and dark mode

### ISSUE THREAD

**Issue by jainaryan04** [SwanandD121/FeatherPerfect_fe#88]
instead of asking users to click on this hyperlink to change between light mode and dark mode, we can add a switch to toggle between the modes. please add gssoc-ext and hacktoberfest-accepted labels @SwanandD121 

![image](https://github.com/user-attachments/assets/6e0a2027-7de6-467c-85eb-077e98cdd62b)
![image](https://github.com/user-attachments/assets/9e946f44-7fac-42e3-b704-54d3ad947229)

**Comment by SwanandD121** [comment]
@jainaryan04 assigned
Make sure the toggle button is same as the one on homepage
