### ISSUE TITLE
[bug]Logout not redirecting to login page

### ISSUE THREAD

**Issue by faiz66388** [SwanandD121/FeatherPerfect_fe#9]
Issue Title:
Logout not redirecting to login page

Description:
When clicking on the logout button, the user is not redirected to the login page as expected. Instead, a white blank page is displayed.

Steps to Reproduce:
Log in to the application.
Click on the logout button.
Observe the behavior.
Expected Behavior:
Upon logging out, the user should be redirected to the login page.

Actual Behavior:
A white blank page is displayed after clicking logout.

Screenshots/Logs:
![image](https://github.com/user-attachments/assets/bd3a767b-eb32-44eb-aa42-bc938f122e83)

**Comment by SwanandD121** [comment]
@faiz66388 go ahead

**Comment by GitWizzz** [comment]
This issue seems to require immediate attention, and I would like to investigate and resolve it. Please let me know if I can take this on.

**Comment by SwanandD121** [comment]
@GitWizzz the issue is already assigned.
