### ISSUE TITLE
Implementing React Hook Form

### ISSUE THREAD

**Issue by 0vai5** [SwanandD121/FeatherPerfect_fe#90]
I would like to propose implementing React Hook Form in our project to manage form state and validation more efficiently. React Hook Form provides a way to manage form inputs and validation with less boilerplate code, resulting in better performance and a smoother development experience.

Performance: It minimizes re-renders, leading to better performance, especially with complex forms.
Simplified Code: The API is easy to use and reduces the amount of code needed for form management.
Built-in Validation: It supports various validation methods, including schema-based validation with libraries like Yup.
Easier Integration: It integrates seamlessly with existing form libraries and UI frameworks.

Please assign this to me, and label it as gssoc-ext and level-2

@SwanandD121

**Comment by 0vai5** [comment]
Assign this to me @sanjay-kv

**Comment by SwanandD121** [comment]
Text me on discord for further discussion 
@swanand_in
