### ISSUE TITLE
Feat : Footer is Needed to Facilitate User for Various Options

### ISSUE THREAD

**Issue by vedanshjainvj** [SwanandD121/FeatherPerfect_fe#98]
**Describe The Feature**
I want to add footer section so that navigation can be facilitated and user-experience  can be Improved.

**Steps To Reproduce**
Steps to reproduce the behavior :
1. Login
2. Go to Homepage
3. Scroll to bottom - footer is missing

**Expected behavior**
A footer will be added in the bottom, so that user can easily access some important routes.

**Screenshots/Videos**
Na

**Additional context**
Must needed : For UX improvement.

**Comment by MohassinHussain** [comment]
Hey @vedanshjainvj I can add the feature i.e., Footer: A footer will be added in the bottom, so that user can easily access some important routes.
